#!/usr/bin/env python3

from pymongo import MongoClient
import datetime
import glob

if __name__ == '__main__':
    CODE = "084990" # 바이로메드

    client = MongoClient()
    db = client['nstock']
    col = db['price']

    for fn in glob.glob('ignore/*.txt'):
        f = open(fn, 'r')
        for line in f.readlines():
            line = line.strip()
            tok = line[len(line) - 22 : len(line)].split()
            dt = datetime.datetime.strptime(tok[0] + ' ' + tok[1], '%Y%m%d %H%M%S')
            price = int(tok[2])
            col.insert_one({ 'code': CODE, 'dt': dt, 'price': price })
        f.close()

